// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateProjectRequestStatus.
const (
	CreateProjectRequestStatusActive   CreateProjectRequestStatus = "active"
	CreateProjectRequestStatusArchived CreateProjectRequestStatus = "archived"
	CreateProjectRequestStatusInactive CreateProjectRequestStatus = "inactive"
)

// Defines values for ProjectStatus.
const (
	ProjectStatusActive   ProjectStatus = "active"
	ProjectStatusArchived ProjectStatus = "archived"
	ProjectStatusInactive ProjectStatus = "inactive"
)

// Defines values for UpdateProjectRequestStatus.
const (
	Active   UpdateProjectRequestStatus = "active"
	Archived UpdateProjectRequestStatus = "archived"
	Inactive UpdateProjectRequestStatus = "inactive"
)

// Account defines model for Account.
type Account struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`
	UpdatedAt time.Time           `json:"updated_at"`
}

// AccountListResponse defines model for AccountListResponse.
type AccountListResponse struct {
	Accounts []Account `json:"accounts"`
	Limit    int       `json:"limit"`
	Offset   int       `json:"offset"`
	Total    int       `json:"total"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	Email openapi_types.Email `json:"email"`
	Name  string              `json:"name"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Description *string                     `json:"description,omitempty"`
	Name        string                      `json:"name"`
	Status      *CreateProjectRequestStatus `json:"status,omitempty"`
}

// CreateProjectRequestStatus defines model for CreateProjectRequest.Status.
type CreateProjectRequestStatus string

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Project defines model for Project.
type Project struct {
	AccountId   openapi_types.UUID `json:"account_id"`
	CreatedAt   time.Time          `json:"created_at"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Status      ProjectStatus      `json:"status"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// ProjectStatus defines model for Project.Status.
type ProjectStatus string

// ProjectListResponse defines model for ProjectListResponse.
type ProjectListResponse struct {
	Limit    int       `json:"limit"`
	Offset   int       `json:"offset"`
	Projects []Project `json:"projects"`
	Total    int       `json:"total"`
}

// UpdateAccountRequest defines model for UpdateAccountRequest.
type UpdateAccountRequest struct {
	Email *openapi_types.Email `json:"email,omitempty"`
	Name  *string              `json:"name,omitempty"`
}

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	Description *string                     `json:"description,omitempty"`
	Name        *string                     `json:"name,omitempty"`
	Status      *UpdateProjectRequestStatus `json:"status,omitempty"`
}

// UpdateProjectRequestStatus defines model for UpdateProjectRequest.Status.
type UpdateProjectRequestStatus string

// AccountID defines model for AccountID.
type AccountID = openapi_types.UUID

// ProjectID defines model for ProjectID.
type ProjectID = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListAccountsParams defines parameters for ListAccounts.
type ListAccountsParams struct {
	// Limit Number of items to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// Limit Number of items to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = UpdateAccountRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectRequest
