openapi: 3.0.3
info:
  title: JWT Auth API
  description: RESTful API for managing accounts and projects
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Development server
  - url: https://api.example.com/api/v1
    description: Production server

tags:
  - name: Health
    description: Health check endpoints
  - name: Accounts
    description: Account management endpoints
  - name: Projects
    description: Project management endpoints

paths:
  /health:
    get:
      operationId: GetHealth
      summary: Health check
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok

  /accounts:
    post:
      operationId: CreateAccount
      summary: Create a new account
      tags:
        - Accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

    get:
      operationId: ListAccounts
      summary: List accounts
      tags:
        - Accounts
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
          description: Number of items to return
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
            minimum: 0
          description: Number of items to skip
      responses:
        '200':
          description: List of accounts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountListResponse'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /accounts/{account_id}:
    get:
      operationId: GetAccount
      summary: Get an account by ID
      tags:
        - Accounts
      parameters:
        - $ref: '#/components/parameters/AccountID'
      responses:
        '200':
          description: Account details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      operationId: UpdateAccount
      summary: Update an account
      tags:
        - Accounts
      parameters:
        - $ref: '#/components/parameters/AccountID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAccountRequest'
      responses:
        '200':
          description: Account updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      operationId: DeleteAccount
      summary: Delete an account
      tags:
        - Accounts
      parameters:
        - $ref: '#/components/parameters/AccountID'
      responses:
        '204':
          description: Account deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /accounts/{account_id}/projects:
    post:
      operationId: CreateProject
      summary: Create a new project
      tags:
        - Projects
      parameters:
        - $ref: '#/components/parameters/AccountID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjectRequest'
      responses:
        '201':
          description: Project created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    get:
      operationId: ListProjects
      summary: List projects for an account
      tags:
        - Projects
      parameters:
        - $ref: '#/components/parameters/AccountID'
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
          description: Number of items to return
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
            minimum: 0
          description: Number of items to skip
      responses:
        '200':
          description: List of projects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectListResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /accounts/{account_id}/projects/{project_id}:
    get:
      operationId: GetProject
      summary: Get a project by ID
      tags:
        - Projects
      parameters:
        - $ref: '#/components/parameters/AccountID'
        - $ref: '#/components/parameters/ProjectID'
      responses:
        '200':
          description: Project details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      operationId: UpdateProject
      summary: Update a project
      tags:
        - Projects
      parameters:
        - $ref: '#/components/parameters/AccountID'
        - $ref: '#/components/parameters/ProjectID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProjectRequest'
      responses:
        '200':
          description: Project updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      operationId: DeleteProject
      summary: Delete a project
      tags:
        - Projects
      parameters:
        - $ref: '#/components/parameters/AccountID'
        - $ref: '#/components/parameters/ProjectID'
      responses:
        '204':
          description: Project deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  parameters:
    AccountID:
      in: path
      name: account_id
      required: true
      schema:
        type: string
        format: uuid
      description: Account ID

    ProjectID:
      in: path
      name: project_id
      required: true
      schema:
        type: string
        format: uuid
      description: Project ID

  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        email:
          type: string
          format: email
          example: user@example.com
        name:
          type: string
          example: John Doe
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - email
        - name
        - created_at
        - updated_at

    CreateAccountRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        name:
          type: string
          example: John Doe
      required:
        - email
        - name

    UpdateAccountRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        name:
          type: string
          example: John Doe

    AccountListResponse:
      type: object
      properties:
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/Account'
        total:
          type: integer
          example: 100
        limit:
          type: integer
          example: 10
        offset:
          type: integer
          example: 0
      required:
        - accounts
        - total
        - limit
        - offset

    Project:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        account_id:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174001
        name:
          type: string
          example: My Project
        description:
          type: string
          example: This is a sample project
        status:
          type: string
          enum: [active, inactive, archived]
          example: active
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - account_id
        - name
        - status
        - created_at
        - updated_at

    CreateProjectRequest:
      type: object
      properties:
        name:
          type: string
          example: My Project
        description:
          type: string
          example: This is a sample project
        status:
          type: string
          enum: [active, inactive, archived]
          example: active
      required:
        - name

    UpdateProjectRequest:
      type: object
      properties:
        name:
          type: string
          example: My Updated Project
        description:
          type: string
          example: This is an updated project description
        status:
          type: string
          enum: [active, inactive, archived]
          example: active

    ProjectListResponse:
      type: object
      properties:
        projects:
          type: array
          items:
            $ref: '#/components/schemas/Project'
        total:
          type: integer
          example: 50
        limit:
          type: integer
          example: 10
        offset:
          type: integer
          example: 0
      required:
        - projects
        - total
        - limit
        - offset

    Error:
      type: object
      properties:
        error:
          type: string
          example: Error message
      required:
        - error

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Conflict:
      description: Conflict with existing resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
